filebeat.inputs:
- type: container
  paths:
    - /var/lib/docker/containers/*/*.log
  processors:
    - add_docker_metadata: ~
    - drop_event:
        when:
          not:
            contains:
              container.labels.logs_service: "backend" # Only pick up backend logs

# To enrich logs with a service name based on the label
processors:
  - add_fields:
      target: '' # Add to root
      fields:
        log_source_service: backend # Hardcode for this specific filebeat instance
        # Or dynamically from label if preferred and works:
        # log_source_service: "${data.container.labels.logs_service}"

#----------------------------- Redis output --------------------------------
output.redis:
  hosts: ["logging-redis:6379"]  # CRITICAL: Must match your service name in docker-compose-elk.yml
  key: "backend_logs"            # CRITICAL: Must match what Logstash input is listening for
  db: 0
  datatype: list
  codec.json:
    pretty: false
    escape_html: false
  # worker: 1 # Default is 1, can be increased if needed
  # bulk_max_size: 2048 # Default

#----------------------------- Logging (Filebeat's own logs) --------------------------------
logging.level: debug
logging.selectors: ["redis", "publisher"] # Crucial for detailed Redis output logs
logging.to_files: false # Send Filebeat's own logs to stdout for Docker
logging.to_stderr: true  # Ensure errors are visible in docker logs

fields:
  log_source_service: "backend"
fields_under_root: true 