filebeat.inputs:
- type: container
  paths:
    - /var/lib/docker/containers/*/*.log
  processors:
    - add_docker_metadata: {}
    - drop_event:
        when:
          not:
            equals:
              container.labels.logs.service: "frontend"
  # Vite logs are usually single line, but adjust if needed
  # multiline.pattern: '^\s'
  # multiline.negate: false
  # multiline.match: after

output.redis:
  hosts: ["logging-redis:6379"]
  key: "frontend_logs" # Unique key
  db: 0
  timeout: 5s

fields:
  log_source_service: "frontend"
fields_under_root: true

logging.level: info 