filebeat.inputs:
- type: container
  paths:
    - /var/lib/docker/containers/*/*.log
  processors:
    - add_docker_metadata: {}
    - drop_event:
        when:
          not:
            equals:
              container.labels.logs.service: "nginx"
  # Nginx logs are typically single line per event.
  # If you have custom Nginx log formats that are multiline, adjust here.

output.redis:
  hosts: ["logging-redis:6379"]
  key: "nginx_logs" # Unique key
  db: 0
  timeout: 5s

fields:
  log_source_service: "nginx"
fields_under_root: true

logging.level: info 